### ISSUE TITLE
One Approach

### ISSUE THREAD

**Issue by m-n** [mabragor/nice-error-strings#1]
I noticed this project come up as a stub, so I thought I'd mention an approach I [used](https://github.com/m-n/dishes/blob/16b58bbafa6bb72a464b227dce476231902660aa/dishes.lisp#L106-L116): add a reader macro that does essentially `#.(format nil string)`. This lets you do things like:

``` lisp
(error #"Single line ~
       error message.")
;; reads as:
(error "Single line error message.")

;; and
(error #"Double line ~@
       error message.")
;; reads as
(error "Double line
error message.")
```

**Comment by mabragor** [comment]
Yes, I thought about exactly this, only more LaTeX-ish -- the string 
reader that would read single line bread as just a space,
and double line break as usual line break.

Is dishes on quicklisp? It not, did you consider submitting it?)

Then, instead of writing the full project I could just submit you a pull 
request.

**Comment by m-n** [comment]
It isn't, but I could submit it.

Does dishes' interface work for you? In particular dishes exports the reader macro functions themselves, instead of an activating `enable` macro. The functions look for `(dishes:closer char)` to terminate parsing, instead of hard coding the start / end character -- that allows them to work when they are set to arbitrary macro characters. 

If so, I would be happy to take a patch and submit it to Quicklisp.

**Comment by luismbo** [comment]
`ERROR` takes a format string already. Did you consider using that capability?

``` lisp
CL-USER> (error "Imagine this is a very long line; I'm ~
                 going to split it in two.")
```

=>

```
Imagine this is a very long line; I'm going to split it in two.
   [Condition of type SIMPLE-ERROR]
```

**Comment by mabragor** [comment]
Thanks a lot, I didn't know about ~ (just tilde without anything) directive to format.
That totally solves the problem I had.
